# Generated by Django 2.2.4 on 2019-08-24 10:17

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_flat_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owners_phone_pure',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+79739237643', max_length=128, region='RU'),
            preserve_default=False,
        ),
    ]
