# Generated by Django 2.2.4 on 2019-08-24 13:16

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20190824_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='owners_phone_pure',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='Нормализированный номер владельца'),
        ),
    ]
