# Generated by Django 2.2.4 on 2019-08-24 12:22

from django.db import migrations


def flat_owners_to_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        Owner.objects.create(
            name=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owners_phone_pure=flat.owners_phone_pure,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20190824_1453'),
    ]

    operations = [
        migrations.RunPython(flat_owners_to_owner)
    ]
