# Generated by Django 2.2.4 on 2019-08-24 13:27

from django.db import migrations


def flat_owners_to_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        owner_obj, created = Owner.objects.get_or_create(
            name=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owners_phone_pure=flat.owners_phone_pure,
        )
        owner_obj.flats.set(flat)
        flat.owners.set(owner_obj)
        flat.save()
        owner_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_flat_owners'),
    ]

    operations = [
        migrations.RunPython(flat_owners_to_owner)
    ]
